<a href="https://colab.research.google.com/github/katherine0888/LinearAlgebra_2ndSem/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for CHE
## Laboratory Matrices

#Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

##Matrices

######The notation and use of matrices is probably one of the fundamentals of modern computing.Matrices are also handy representions of complex equations or multiple inter-related equations

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C=\left\{
\right. $$


:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix}1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}
$$



Declaring Matrices


$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A= np.array([
    [1,2],
    [3,1]
])
describe_mat(A)


Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G= np. array([
              

#Categorizing Matrices

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array ([
 1,3,2,-4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array ([
    [1,2,3,-4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)
                    

Matrix:
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix 

col_mat = np.array([
    [1],
    [9],
    [5]
]) ## this is a 2-D Matrix with a shape (1,5)
describe_mat(col_mat)

Matrix:
[[1]
 [9]
 [5]]

Shape:	(3, 1)
Rank:	2
Ia Square: False



Square Matrices

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIa Square: {is_square}\n')
  

In [ ]:
square_mat = np. array ([
    [2,3,4],
    [1,2,3],
    [7,8,9]
])

non_square_mat = np. array ([
      [2,3,4],
      [1,2,3] 
])
describe_mat(square_mat) 
describe_mat(non_square_mat)                     

Matrix:
[[2 3 4]
 [1 2 3]
 [7 8 9]]

Shape:	(3, 3)
Rank:	2
Ia Square: True

Matrix:
[[2 3 4]
 [1 2 3]]

Shape:	(2, 3)
Rank:	2
Ia Square: False



Null Matrix

In [30]:
def describe_mat(matrix):
    if matrix.size > 0:
      is_square = True if matrix.shape[0] == matrix.shape[1] else False
      print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
      print('Matrix is Null')

In [31]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


In [26]:
zero_mat_row =np.zeros ((2,3))
zero_mat_sqr= np.zeros((3,3,))
zero_mat_rct=np.zeros ((4,3))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangle Matrix: \n{zero_mat_row}')


Zero Row Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Zero Rectangle Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
ones_mat_row =np.ones ((2,3))
ones_mat_sqr= np.ones((3,3,))
ones_mat_rct=np.ones ((4,3))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangle Matrix: \n{ones_mat_row}')

Ones Row Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ones Rectangle Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]


Diagonal Matrix

In [34]:
np.array ([
  [3,5,1],
  [0,3,1],
  [7,8,9]         
])

array([[3, 5, 1],
       [0, 3, 1],
       [7, 8, 9]])

In [32]:
d = np.diag([2,3,4,5])
d.shape[0]==d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

identity


In [35]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [36]:
np.identity (1)

array([[1.]])

Upper Triangular Matrix

In [41]:
np.array([
  [2,3,4,5],
  [1,1,8,1],
  [0,0,8,0],
  [0,0,0,3]
])

array([[2, 3, 4, 5],
       [1, 1, 8, 1],
       [0, 0, 8, 0],
       [0, 0, 0, 3]])

Lower Triangular Matrix

In [ ]:
np.array([

PRACTICES

1. Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [42]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations


In [43]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

Matrix Algebra

aqddition

In [45]:
A= np. array([
      [2,2],
      [3,4],
      [5,6]
])
B= np.array([
      [2,2],
      [3,4],
      [5,6] 
])
A+B     

array([[ 4,  4],
       [ 6,  8],
       [10, 12]])

subtrac tion


In [46]:
A= np. array([
      [2,2],
      [3,4],
      [5,6]
])
B= np.array([
      [2,2],
      [3,4],
      [5,6] 
])
A-B     

array([[0, 0],
       [0, 0],
       [0, 0]])

In [47]:
3-B

array([[ 1,  1],
       [ 0, -1],
       [-2, -3]])

Element Wise Multiplication

In [48]:
A*B

array([[ 4,  4],
       [ 9, 16],
       [25, 36]])

In [49]:
3*A

array([[ 6,  6],
       [ 9, 12],
       [15, 18]])